Keynua/slate

source/localizable/index.html.md
Add Keynua Signature Webhook V2
=> Add Keynua Signature Webhook V2

source/localizable/index.html.md
=> feat: add cavali attribute description

source/localizable/index.html.md
=> feat: add alert attributes

source/localizable/index.html.md
=> feat: show contract alerts

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/dev_deploy.yml, Gemfile
=> fix: update ruby

source/localizable/index.html.md
=> feat: add max_attempts status

source/localizable/index.html.md
=> feat: verification api v2

source/localizable/index.html.md
=> feat: revert verification api v2

source/localizable/index.html.md
=> feat: add smile type

source/localizable/index.html.md
=> feat: contract approval api

source/localizable/index.html.md
=> feat: add maxNamesDifference attribute

source/localizable/index.html.md
=> feat: add placeholders description

source/localizable/index.html.md
=> feat: upload buttons description

source/localizable/index.html.md
=> feat: decline contract description

source/localizable/index.html.md
=> feat: ocr data attributes description

source/localizable/index.html.md
=> feat: add documentScanVersion attribute description

source/localizable/index.html.md
=> feat: add contract input provided webhook description

source/localizable/index.html.md
=> feat update description

source/localizable/index.html.md
=> feat: add sex and nationality fields

source/localizable/index.html.md
=> feat: remove belcorp

source/localizable/index.html.md
=> feat: basic integration flow

source/localizable/index.html.md
I took the opportunity to change all "dev" references to "stg"
=> feat: modify livenessInput item value

source/localizable/index.html.md
=> feat: add pagination parameters to contract API endpoint

.github/workflows/build.yml, source/localizable/index.html.md
=> feat: change error types for livenessinput

source/localizable/index.html.md
=> feat: add address match score
